apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
        - name: streamlit-app
          image: angel/testing_ui:latest
          ports:
            - containerPort: 8501
          volumeMounts:
            - name: saved-model
              mountPath: /app/saved_model
      volumes:
        - name: saved-model
          persistentVolumeClaim:
            claimName: saved-model-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: LoadBalancer
  selector:
    app: streamlit-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
