apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-job
  labels:
    app: model-training
spec:
  backoffLimit: 3 # Self Healing
  template:
    metadata:
      labels:
        app: model-training
    spec:
      restartPolicy: OnFailure # Restart if fails
      containers:
        - name: model-training-container
          image: zerook2005/model-training:latest
          imagePullPolicy: IfNotPresent
          command:
            ["/bin/sh", "-c", "python3 /app/python_scripts/model_training.py"]
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: cleaned-data
              mountPath: "/datasets/cleaned_datasets"
              readOnly: false
            - name: saved-models
              mountPath: "/saved_model"
              readOnly: false
      volumes:
        - name: cleaned-data
          persistentVolumeClaim:
            claimName: cleaned-data-pvc
        - name: saved-models
          persistentVolumeClaim:
            claimName: saved-model-pvc
