paths:
  cleaned_train: "/datasets/cleaned_datasets/cleaned_train_data.csv" # Path to the clenaed training dataset
  model_output: "/saved_model/" # Directory to save trained models

parameters:
  target_column: "Survived" # Target variable
  test_size: 0.2 # 80% is for training; 20% for testing
  random_state: 42
