apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-deployment
  labels:
    app: prediction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prediction
  template:
    metadata:
      labels:
        app: prediction
    spec:
      containers:
        - name: prediction-container
          image: zerook2005/prediction-image:latest
          imagePullPolicy: Never
          command:
            [
              "python3",
              "/app/python_scripts/prediction.py",
              "--batch",
              "/saved_model/input.csv",
            ]
          volumeMounts:
            - name: saved-models
              mountPath: /saved_model
      volumes:
        - name: saved-models
          persistentVolumeClaim:
            claimName: saved-model-pvc
