apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-deployment
  labels:
    app: prediction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction
  template:
    metadata:
      labels:
        app: prediction
    spec:
      containers:
        - name: prediction-container
          image: zerook2005/prediction-image:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: saved-model
              mountPath: "/app/saved_model"
          command: ["python"]
          args: ["python_scripts/prediction.py"]
      volumes:
        - name: saved-model
          persistentVolumeClaim:
            claimName: saved-model-pvc # Uses PVC for saved model
