apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-optimization-deployment
  labels:
    app: model-optimization
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-optimization
  template:
    metadata:
      labels:
        app: model-optimization
    spec:
      containers:
        - name: model-optimization-container
          image: zerook2005/model-optimization:latest
          imagePullPolicy: IfNotPresent
          command:
            [
              "/bin/sh",
              "-c",
              "python3 /app/python_scripts/model_optimization.py",
            ]
          volumeMounts:
            - name: cleaned-data
              mountPath: "/datasets/cleaned_datasets"
            - name: saved-models
              mountPath: "/saved_model"
      volumes:
        - name: cleaned-data
          persistentVolumeClaim:
            claimName: cleaned-data-pvc
        - name: saved-models
          persistentVolumeClaim:
            claimName: saved-model-pvc
