# This file is a YAML file for creating the Persistent Volume used for storing trained models

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-model
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/saved_model" # Standardized path
    type: DirectoryOrCreate
