apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-raw
spec:
  capacity:
    storage: 100Mi # Adjust if needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/datasets/raw_datasets" # Standardized path
    type: DirectoryOrCreate
