# This file is a YAML file for creating the Persistent Volume used for storing the Raw Data

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-raw
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/datasets/raw_datasets" # Standardized path
    type: DirectoryOrCreate
