apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cleaned-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
  volumeName: pv-cleaned
