# This file is a YAML file for creating the Persistent Volume claim used to access the model pv

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saved-model-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
  volumeName: pv-model
