# Note! This Deployment YAML is retained for reference, but the project uses a Job-based approach instead.
#
# This deployment file is responsible for managing the data preprocessing container within a Kubernetes cluster.
# It defines the specifications for how the container should be deployed, including scaling, resource allocation, volume mounting, and execution commands.
# - This deployment ensures that two replicas of the data preprocessing container run simultaneously.
# - Kubernetes manages the pods and ensures high availability.
 


apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-preprocessing-deployment
  labels:
    app: data-preprocessing
spec:
  replicas: 2 # Number of pod replicas for scaling
  selector:
    matchLabels:
      app: data-preprocessing
  template:
    metadata:
      labels:
        app: data-preprocessing
    spec:
      containers:
        - name: data-preprocessing-container
          image: thisisangelz/data-preprocessing:latest
          imagePullPolicy: IfNotPresent
          command:
            [
              "/bin/sh",
              "-c",
              "python3 /app/python_scripts/data_preprocessing.py",
            ]
          resources: # Resource allocation for the container
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 8080 # Port the container will expose
          volumeMounts:
            - name: raw-data
              mountPath: "/datasets/raw_datasets"
              readOnly: false
            - name: cleaned-data
              mountPath: "/datasets/cleaned_datasets"
              readOnly: false
      volumes:
        - name: raw-data
          persistentVolumeClaim:
            claimName: raw-data-pvc # Uses PVC for raw datasets
        - name: cleaned-data
          persistentVolumeClaim:
            claimName: cleaned-data-pvc # Uses PVC for cleaned datasets
