apiVersion: batch/v1
kind: Job
metadata:
  name: data-preprocessing-job
  labels:
    app: data-preprocessing
spec:
  template:
    metadata:
      labels:
        app: data-preprocessing
    spec:
      restartPolicy: Never # Ensures the job runs only once per pod
      containers:
        - name: data-preprocessing-container
          image: zerook2005/data-preprocessing:latest # Replace with actual image name
          imagePullPolicy: IfNotPresent
          command:
            [
              "/bin/sh",
              "-c",
              "python3 /app/python_scripts/data_preprocessing.py",
            ]
          resources: # Resource allocation for the container
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: raw-data
              mountPath: "/datasets/raw_datasets"
              readOnly: false
            - name: cleaned-data
              mountPath: "/datasets/cleaned_datasets"
              readOnly: false
      volumes:
        - name: raw-data
          persistentVolumeClaim:
            claimName: raw-data-pvc # Uses PVC for raw datasets
        - name: cleaned-data
          persistentVolumeClaim:
            claimName: cleaned-data-pvc # Uses PVC for cleaned datasets
