apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
  labels:
    app: streamlit-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
        - name: streamlit-app
          image: zerook2005/testing_ui:latest
          imagePullPolicy: IfNotPresent
          command:
            [
              "streamlit",
              "run",
              "/app/python_scripts/app.py",
              "--server.port=8501",
              "--server.address=0.0.0.0",
            ]
          resources: # Resource allocation for the container
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 8501
          volumeMounts:
            - name: saved-models
              mountPath: /saved_model
      volumes:
        - name: saved-models
          persistentVolumeClaim:
            claimName: saved-model-pvc
