# This file defines how the Streamlit-based Titanic survival prediction app 
# will be deployed on a Kubernetes cluster.
#
# Key Features:
# - Runs 3 replicas for high availability.
# - Uses RollingUpdate to ensure zero downtime during updates.
# - Allocates resource limits to prevent excessive CPU/memory usage.
# - Mounts a Persistent Volume (PVC) for storing the trained model.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
  labels:
    app: streamlit-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streamlit-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
        - name: streamlit-app
          image: zerook2005/app:latest
          imagePullPolicy: IfNotPresent
          command:
            [
              "streamlit",
              "run",
              "/app/python_scripts/app.py",
              "--server.port=8501",
              "--server.address=0.0.0.0",
            ]
          resources: # Resource allocation for the container
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 8501
          volumeMounts:
            - name: saved-models
              mountPath: /saved_model
      volumes:
        - name: saved-models
          persistentVolumeClaim:
            claimName: saved-model-pvc
