# This file defines a LoadBalancer service to expose the Streamlit web app.
#
# Key Features:
# - Uses LoadBalancer to provide external access.
# - Forwards TCP traffic on port 8501.
# - Uses ClientIP session affinity to maintain user state.

apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: streamlit-app
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  sessionAffinity: ClientIP
